### ISSUE TITLE
Shop Site - Buttons(Filter)

### ISSUE THREAD

**Issue by netodo** [Forket/pogea-racing.com#14]
Please no red and green buttons (Filter) ... please styling of buttons like all other buttons :)

**Comment by Forket** [comment]
And what is the style of all other buttons? :) because in some places they are also red. :)


Sent from Mobile

Thanks and regards,
Aleksandr Sen
CEO | Expedition PM
Mobile: +48 532 292 764
Skype: aleksandr.sen
Email: alex@sen.pm
Social: LinkedIn | Google+
 
EXPEDITION.PM | KNOWLEDGEMAP.PM

Dnia 03 Nov 2015 o godz. 14:26 netodo <notifications@github.com> napisał(a):

**Comment by netodo** [comment]
![buttons_ff](https://cloud.githubusercontent.com/assets/15340006/10952395/c8eac368-8342-11e5-94f1-1447228e7242.png)

like this ... first 3 in #000... and last in red #dd3333

**Comment by Forket** [comment]
Done. Please approve and close issue if OK

**Comment by netodo** [comment]
i think its ok
